# set jekyll theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: "Tiffany Liang"
author: "me"
description: "A personal showcase of my work."
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true

# Menu
navigation:
- {file: "index.html", title:"Home", icon: home}

external:
- {title: LinkedIn, url:""}